jobs:
  build:
    docker:
      - image: kalpibakto/pinaka:1.3
    parallelism: 1
    steps:
      - checkout
      - run:
          name: app
          command: |
            NCPU=`nproc --all`
            RAM=$(free -g | grep Mem: | awk '{print $2}')
            
